// Golden-fixture contract suite — Termhalla's hand-mirrored Orky constants asserted against REAL
// Orky-emitted artifacts (tests/fixtures/orky-contract/), generated by actually running the producer
// (the gatekeeper CLI) via tools/generate-orky-contract-fixtures.mjs and COMMITTED, so this suite runs
// green without Orky present. This is the test that finally catches phase-list / OSC-framing drift:
// re-running the generator against a newer Orky refreshes the fixtures, and any divergence from the
// mirrors below turns this suite red — closing the gap the provenance caveats in
// docs/features/orky-status.md ("upstream drift is a manual data-update follow-up") could only warn
// about. It still cannot catch LIVE drift between regenerations — the fixtures are a snapshot.
//
// EXTENDED through the 0015-orky-contract-v2-refresh TESTS phase (REQ-105 / REQ-106): the final
// describe-block pins the REGENERATED v2 fixture's shape (contract_version 2, phase_order ending
// 'human-review', the new finding_resolution / producer_tiers blocks, state.gate_fields gaining
// firstAt) and re-pins that ORKY_PHASES needed NO change. It runs RED against the committed v1
// fixture until TASK-103 regenerates all four fixtures in ONE run of the generator against plugin
// 0.30.0 — the fixtures are real producer output and are NEVER hand-edited (binding decision 3).
// Every pre-existing assertion above it is byte-for-byte unchanged (they are version-agnostic).
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { ORKY_PHASES, gateN, normalizeFeatureRaw, parseOrkyTimestamp } from '@shared/orky-status'
import { OrkyOscParser, ORKY_OSC, MAX_PAYLOAD_BYTES } from '../../src/main/status/orky-osc-parser'

const FIXTURE_DIR = 'tests/fixtures/orky-contract'
const fixture = (name: string): string => readFileSync(resolve(process.cwd(), FIXTURE_DIR, name), 'utf8')

interface Contract {
  contract_version: number
  phases: string[]
  osc: { code: number; v: number; terminator: string; max_payload_bytes: number; fields: string[] }
}
const contract = JSON.parse(fixture('contract.json')) as Contract

describe('gatekeeper contract vs. Termhalla mirrors (the drift catcher)', () => {
  it('contract.phases deep-equals ORKY_PHASES — the hand-mirrored phase list has not drifted', () => {
    // ORKY_PHASES mirrors DRIVER_WORK_PHASES / the recorded gate keys (see the provenance caveat in
    // src/shared/orky-status.ts) — `contract.phases` IS that list, straight from the producer.
    expect([...ORKY_PHASES]).toEqual(contract.phases)
  })

  it('contract.osc.code is 9999 and the parser prefix is built from exactly that code', () => {
    expect(contract.osc.code).toBe(9999)
    expect(ORKY_OSC).toBe(`\x1b]${contract.osc.code};`)
  })

  it('contract.osc.max_payload_bytes equals the parser\'s MAX_PAYLOAD_BYTES', () => {
    expect(contract.osc.max_payload_bytes).toBe(MAX_PAYLOAD_BYTES)
  })
})

describe('real osc-heartbeat bytes parse through OrkyOscParser', () => {
  it('the captured escape sequence decodes to exactly one sane heartbeat', () => {
    const bytes = fixture('osc-heartbeat.bin') // ASCII-safe payload; utf8 decode is byte-faithful
    const heartbeats = new OrkyOscParser().push(bytes)
    expect(heartbeats).toHaveLength(1)
    const hb = heartbeats[0]
    expect(hb.feature).toBe('0001-golden')
    expect(typeof hb.phase).toBe('string')
    expect(hb.gateM).toBe(contract.phases.length) // the wire's "N/M" total agrees with the phase list
    expect(hb.gateN).toBeGreaterThanOrEqual(1)    // the generator really passed gates before emitting
    expect(typeof hb.needsHuman).toBe('boolean')
  })
})

describe('real state.json / active.json normalize through the shared mappers', () => {
  it('state.json normalizes without falling back to empty defaults — the recorded gates are recognized', () => {
    const raw = normalizeFeatureRaw(JSON.parse(fixture('state.json')))
    expect(raw.feature).toBe('0001-golden')            // not the '' fallback
    expect(raw.phase).not.toBeNull()                   // not the null fallback
    expect(raw.gates['brainstorm']?.passed).toBe(true) // canonical gate keys land where gateN looks
    expect(gateN(raw.gates)).toBeGreaterThanOrEqual(2) // brainstorm (record) + tests (real check run)
  })

  it('active.json carries feature/phase/lastTickAt (tz-parseable) and the newer `runs` map is tolerated', () => {
    const active = JSON.parse(fixture('active.json')) as Record<string, unknown>
    expect(typeof active.feature).toBe('string')
    expect((active.feature as string).endsWith('0001-golden')).toBe(true)
    expect(typeof active.phase).toBe('string')
    expect(parseOrkyTimestamp(active.lastTickAt)).not.toBeNull()
    // active.json now ALSO carries a `runs` map (one entry per concurrent run) — extra fields the
    // consumers must tolerate, never reject; its presence is pinned here so a consumer-side "strict
    // shape" regression would be caught against real producer output.
    expect(active.runs).toBeTypeOf('object')
    expect(Object.keys(active.runs as Record<string, unknown>).length).toBeGreaterThanOrEqual(1)
  })
})

// ── 0015-orky-contract-v2-refresh additions (REQ-105 / REQ-106) ───────────────────────────────────
// A tolerant untyped view of the SAME committed contract.json — the v2 keys are absent from the v1
// snapshot (the RED state), so they are read via Record access, never via the typed interface above.
const contractRaw = JSON.parse(fixture('contract.json')) as Record<string, unknown>

describe('the committed contract.json is the regenerated v2 producer snapshot (0015 REQ-105 / REQ-106)', () => {
  it('TEST-711 REQ-105: contract_version 2; phase_order ends \'human-review\' (intake still first); finding_resolution + producer_tiers blocks present; state.gate_fields gained firstAt', () => {
    // The verified v1→v2 diff, pinned field-by-field against the COMMITTED fixture. Runs RED until
    // TASK-103 regenerates the fixtures from plugin 0.30.0 — never hand-edit them to satisfy this.
    expect(contractRaw.contract_version).toBe(2)

    const phaseOrder = contractRaw.phase_order
    expect(Array.isArray(phaseOrder)).toBe(true)
    const po = phaseOrder as unknown[]
    expect(po[po.length - 1]).toBe('human-review') // v2 renamed the trailing 'human'
    expect(po[0]).toBe('intake')                   // intake remains the still-live intentional difference

    // the two NEW top-level v2 blocks are present in the snapshot (presence pinned here; Termhalla
    // adopts finding_resolution for display and deliberately adopts NOTHING of producer_tiers —
    // that non-adoption is a review-time scope check, per REQ-112, not a frozen absence-guard)
    expect(contractRaw.finding_resolution, 'v2 contract must carry finding_resolution').toBeTypeOf('object')
    expect(contractRaw.finding_resolution).not.toBeNull()
    expect(contractRaw, 'v2 contract must carry producer_tiers').toHaveProperty('producer_tiers')

    // state.gate_fields gained firstAt (additive; consumers tolerate it — no consumer change)
    const state = contractRaw.state as Record<string, unknown>
    expect(state).toBeTypeOf('object')
    expect(state.gate_fields).toContain('firstAt')
  })

  it('TEST-712 REQ-106: v2 did NOT change `phases` — the fixture still deep-equals ORKY_PHASES and the exported constant literal is textually unchanged', () => {
    // the same deep-equal the version-agnostic drift catcher above pins, re-asserted under the v2
    // snapshot: 8 entries, ending 'human-review'
    expect(contractRaw.phases).toEqual([...ORKY_PHASES])
    expect(ORKY_PHASES).toHaveLength(8)
    expect(ORKY_PHASES[ORKY_PHASES.length - 1]).toBe('human-review')
    // and the constant ITSELF must not have been edited (REQ-106's "textually unchanged" half):
    // the exact literal block is still in src/shared/orky-status.ts, byte-for-byte.
    // EOL-normalized (the checkout may be CRLF on Windows) — the pin is about the LITERAL, not EOLs
    const src = readFileSync(resolve(process.cwd(), 'src/shared/orky-status.ts'), 'utf8').replace(/\r\n/g, '\n')
    expect(src).toContain(
      "export const ORKY_PHASES: readonly OrkyPhase[] = [\n" +
      "  'brainstorm', 'spec', 'plan', 'tests', 'implement', 'review', 'doc-sync', 'human-review'\n" +
      "] as const"
    )
  })
})
