// Golden-fixture contract suite — Termhalla's hand-mirrored Orky constants asserted against REAL
// Orky-emitted artifacts (tests/fixtures/orky-contract/), generated by actually running the producer
// (the gatekeeper CLI) via tools/generate-orky-contract-fixtures.mjs and COMMITTED, so this suite runs
// green without Orky present. This is the test that finally catches phase-list / OSC-framing drift:
// re-running the generator against a newer Orky refreshes the fixtures, and any divergence from the
// mirrors below turns this suite red — closing the gap the provenance caveats in
// docs/features/orky-status.md ("upstream drift is a manual data-update follow-up") could only warn
// about. It still cannot catch LIVE drift between regenerations — the fixtures are a snapshot.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { ORKY_PHASES, gateN, normalizeFeatureRaw, parseOrkyTimestamp } from '@shared/orky-status'
import { OrkyOscParser, ORKY_OSC, MAX_PAYLOAD_BYTES } from '../../src/main/status/orky-osc-parser'

const FIXTURE_DIR = 'tests/fixtures/orky-contract'
const fixture = (name: string): string => readFileSync(resolve(process.cwd(), FIXTURE_DIR, name), 'utf8')

interface Contract {
  contract_version: number
  phases: string[]
  osc: { code: number; v: number; terminator: string; max_payload_bytes: number; fields: string[] }
}
const contract = JSON.parse(fixture('contract.json')) as Contract

describe('gatekeeper contract vs. Termhalla mirrors (the drift catcher)', () => {
  it('contract.phases deep-equals ORKY_PHASES — the hand-mirrored phase list has not drifted', () => {
    // ORKY_PHASES mirrors DRIVER_WORK_PHASES / the recorded gate keys (see the provenance caveat in
    // src/shared/orky-status.ts) — `contract.phases` IS that list, straight from the producer.
    expect([...ORKY_PHASES]).toEqual(contract.phases)
  })

  it('contract.osc.code is 9999 and the parser prefix is built from exactly that code', () => {
    expect(contract.osc.code).toBe(9999)
    expect(ORKY_OSC).toBe(`\x1b]${contract.osc.code};`)
  })

  it('contract.osc.max_payload_bytes equals the parser\'s MAX_PAYLOAD_BYTES', () => {
    expect(contract.osc.max_payload_bytes).toBe(MAX_PAYLOAD_BYTES)
  })
})

describe('real osc-heartbeat bytes parse through OrkyOscParser', () => {
  it('the captured escape sequence decodes to exactly one sane heartbeat', () => {
    const bytes = fixture('osc-heartbeat.bin') // ASCII-safe payload; utf8 decode is byte-faithful
    const heartbeats = new OrkyOscParser().push(bytes)
    expect(heartbeats).toHaveLength(1)
    const hb = heartbeats[0]
    expect(hb.feature).toBe('0001-golden')
    expect(typeof hb.phase).toBe('string')
    expect(hb.gateM).toBe(contract.phases.length) // the wire's "N/M" total agrees with the phase list
    expect(hb.gateN).toBeGreaterThanOrEqual(1)    // the generator really passed gates before emitting
    expect(typeof hb.needsHuman).toBe('boolean')
  })
})

describe('real state.json / active.json normalize through the shared mappers', () => {
  it('state.json normalizes without falling back to empty defaults — the recorded gates are recognized', () => {
    const raw = normalizeFeatureRaw(JSON.parse(fixture('state.json')))
    expect(raw.feature).toBe('0001-golden')            // not the '' fallback
    expect(raw.phase).not.toBeNull()                   // not the null fallback
    expect(raw.gates['brainstorm']?.passed).toBe(true) // canonical gate keys land where gateN looks
    expect(gateN(raw.gates)).toBeGreaterThanOrEqual(2) // brainstorm (record) + tests (real check run)
  })

  it('active.json carries feature/phase/lastTickAt (tz-parseable) and the newer `runs` map is tolerated', () => {
    const active = JSON.parse(fixture('active.json')) as Record<string, unknown>
    expect(typeof active.feature).toBe('string')
    expect((active.feature as string).endsWith('0001-golden')).toBe(true)
    expect(typeof active.phase).toBe('string')
    expect(parseOrkyTimestamp(active.lastTickAt)).not.toBeNull()
    // active.json now ALSO carries a `runs` map (one entry per concurrent run) — extra fields the
    // consumers must tolerate, never reject; its presence is pinned here so a consumer-side "strict
    // shape" regression would be caught against real producer output.
    expect(active.runs).toBeTypeOf('object')
    expect(Object.keys(active.runs as Record<string, unknown>).length).toBeGreaterThanOrEqual(1)
  })
})
